#!/usr/bin/env bash
# This script installs Nginx and configures it to return 'Hello World!' on the root URL

# Exit immediately if a command exits with a non-zero status
set -e

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Replace default nginx index.html with Hello World!
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart nginx without using systemctl
service nginx restart
